//! Rust binding for the tree-sitter CQL grammar.
//!
//! The grammar (`grammar.js` at the crate root) is generated by
//! `tree-sitter generate` into `src/parser.c`; `build.rs` compiles it.

use tree_sitter_language::LanguageFn;

extern "C" {
    fn tree_sitter_cql() -> *const ();
}

/// The tree-sitter [`LanguageFn`] for CQL.
pub const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(tree_sitter_cql) };
